### ISSUE TITLE
Incompatibility with browserify-istanbul in karma

### ISSUE THREAD

**Issue by seagoj** [i-like-robots/rewireify#8]
I get the following error when I try to use the rewireify and browserify-istanbul browserify transforms through karma:

```bash
$ karma start

/Users/Admin/code/bot/node_modules/karma-bro/node_modules/browserify/index.js:230
    opts._flags = '_flags' in opts ? opts._flags : self._options;
                              ^
TypeError: Cannot use 'in' operator to search for '_flags' in browserify-istanbul
  at Browserify.transform (/Users/Admin/code/bot/node_modules/karma-bro/node_modules/browserify/index.js:230:31)
  at /Users/Admin/code/bot/node_modules/karma-bro/lib/bro.js:144:19
  at Function.forEach (/Users/Admin/code/bot/node_modules/karma-bro/node_modules/lodash/dist/lodash.js:3297:15)
  at createBundle (/Users/Admin/code/bot/node_modules/karma-bro/lib/bro.js:138:7)
  at framework (/Users/Admin/code/bot/node_modules/karma-bro/lib/bro.js:93:9)
  at Array.invoke [as 0] (/Users/Admin/code/bot/node_modules/karma/node_modules/di/lib/injector.js:75:15)
  at [object Object].get (/Users/Admin/code/bot/node_modules/karma/node_modules/di/lib/injector.js:48:43)
  at /Users/Admin/code/bot/node_modules/karma/lib/server.js:31:14
  at Array.forEach (native)
  at start (/Users/Admin/code/bot/node_modules/karma/lib/server.js:30:21)
  at [object Object].invoke (/Users/Admin/code/bot/node_modules/karma/node_modules/di/lib/injector.js:75:15)
  at Object.exports.start (/Users/Admin/code/bot/node_modules/karma/lib/server.js:310:12)
  at Object.exports.run (/Users/Admin/code/bot/node_modules/karma/lib/cli.js:224:25)
  at requireCliAndRun (/usr/local/lib/node_modules/karma-cli/bin/karma:24:16)
  at /usr/local/lib/node_modules/karma-cli/bin/karma:56:12
  at /usr/local/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:44:21
  at /usr/local/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:119:35
  at /usr/local/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:91:39
  at /usr/local/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:60:30
  at /usr/local/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:20:18
  at Object.oncomplete (fs.js:108:15)
```

**Comment by i-like-robots** [comment]
@seagoj  I'm not sure posting your issue here is the right place, I don't see any mention of Rewireify in the stack trace so I don't think I am able to help.

My advice really would be don't run them together - at least I can't think of a reason to. Istanbul should be  used to measure your production code but Rewireify is an aid to testing.

**Comment by robertlevy** [comment]
istanbul is very often used to measure code coverage of automated testing
